events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    tcp_nopush on;
    server_tokens off;
    client_max_body_size 50m;

    resolver 127.0.0.11 valid=30s ipv6=off;

    access_log /dev/stdout;
    error_log /dev/stderr warn;

    server {
        listen 80;
        listen [::]:80;
        server_name _;

        return 308 https://$host$request_uri;
    }

    server {
        listen 443 ssl default_server;
        listen [::]:443 ssl default_server;
        server_name _;

        include /etc/nginx/certs.d/certbot.conf;

        return 444;
    }

    include /etc/nginx/conf.d/*.conf;
}
