ssl_certificate /certs/certbot/config/live/kuhari.app/fullchain.pem;
ssl_certificate_key /certs/certbot/config/live/kuhari.app/privkey.pem;

add_header Strict-Transport-Security "max-age=63072000" always;
